### ISSUE TITLE
Want to be signed?

### ISSUE THREAD

**Issue by Zedwill96** [karate/fuego-fighters#12]
Hello, I am a coder, I have started my own website, for people to get access to my programs easy, I am looking for programs to feature, and i LOVE yours. I am willing to package and sign your program, and feature it on my website, for free, just let me know your conditions!

**Comment by karate** [comment]
Hello. Thank you for your interest!

I see that you already posted the game in https://pachsoftware.com/other-programs.
This is fine, since you've credited the repository.

Good luck with your website.
